# Runs all the Python SDK tests within the `tests/` directory to check our code

name: CI Tests with CPU build
permissions: read-all

on:
  workflow_dispatch:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev**

concurrency:
  # github.workflow: name of the workflow
  # github.event.pull_request.number || github.ref: pull request number or branch name if not a pull request
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true

jobs:
  pytest-cpu:
    name: pytest (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Missing Developper packages
        run: |
          pip install pytest
          sudo apt -y install cuda-toolkit
      - name: Install and build
        run: |
          export WITH_CUDA=False
          pip install .
      # TODO activate pytests when ready
      # - name: Test with pytest
      #   run: pytest python/tests
